### ISSUE TITLE
set up repo to prepare for csv-to-interactive table workflow

### ISSUE THREAD

**Issue by mdingemanse** [liesenf/opening-up-chatgpt#12]
### Goal
Create a live updated table similar to the one in our paper:

![image](https://github.com/liesenf/awesome-open-chatgpt/assets/9883915/2e9c3f7f-e7a8-4bce-a1d4-52449c1f340d)

### How to get there

The [website](https://github.com/liesenf/awesome-open-chatgpt/tree/Website/projects) branch has a projects folder with 3 CSVs (and a `sample_project.csv` template to create more). These are minimal CSVs that represent the basic data structure we need for each project:

```
project_name,"Stanford Alpaca"
project_link,"https://crfm.stanford.edu/2023/03/13/alpaca.html"
project_notes,""
opencode_class,"open"
opencode_link,""
opencode_notes,""
llmdata_class,"open"
llmdata_link,"https://github.com/tatsu-lab/stanford_alpaca#data-release"
llmdata_notes,""
llmweights_class,"partial"
llmweights_link,""
llmweights_notes,"LLaMA based, copyright status unclear"
```
* `project_` fields contain metadata
* a further set of data fields (`opencode`, `llmdata`, etc.) always comes in threes: 
    * `_class` with three possible values: "open", "partial", "closed". These map onto what is currently  "✓,~,✗" and green/orange/red in the Table in the paper. 
    * `_link` with a URL that documents the source for the class judgement
    * `_notes` that provides explanation and reasoning for the class judgement

### What we need
Roughly, the following:

* A github action, triggered when we close a pull request, that pulls together the latest version of all csvs in the projects folder and merges them into one
* A conversion of that master csv file into a live table, where 
    * `project_name` is a row 
    * data fields (`opencode`, `llmdata`, `llmweights`, etc.) are columns
    * cells get a "✓,~,✗" and a colour depending on the `_class` data field
    * cells contain links that correspond to the `_link` data field
    * the links in the cells contain a `title` attribute that corresponds to the `_notes` data field
* A github action, triggered when the table is updated, that writes it to a github page.

**Comment by liesenf** [comment]
Sample script to merge csvs:

https://gist.github.com/liesenf/43231b4b477a36d674b195fb0a74e8f1
