### ISSUE TITLE
Table: Order projects by degree of openness

### ISSUE THREAD

**Issue by mdingemanse** [liesenf/opening-up-chatgpt#16]
Not clear how projects are ordered right now, but I think ordering by degree of openness makes most sense. 

There are many ways to sort but here's a reasonable start:

1. Count all `_class` fields and assign 1 for `open`, 0.5 for `partial`, 0 for `closed`. That score is openness score. 
2. Order by openness score, with alphabetical ordering for ties

I foresee that we may want to tinker with the weighting here so it would be nice to have this a bit of modular code that is easy to adjust.

I think this is best done in [consolidate_csv.py](https://github.com/liesenf/opening-up-chatgpt/blob/main/scripts/consolidate_csv.py) when the table is created.

**Comment by timjzee** [comment]
Can be closed?

**Comment by mdingemanse** [comment]
This is wonderful, thanks @timjzee!

**Comment by mdingemanse** [comment]
Also, compliments for [making it so modular](https://github.com/liesenf/opening-up-chatgpt/commit/caebbb7595686e5269590c48203528b0a7d89177) that it's easy to tinker with weighting of both features and classes!
